"""business layer: rules/assets/tasks + qr review cols

Revision ID: 7bb304f4669b
Revises: e2968b037cce
Create Date: 2026-08-23 12:27:04.715169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7bb304f4669b'
down_revision: Union[str, Sequence[str], None] = 'e2968b037cce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_task',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('workflow_id', sa.String(length=64), nullable=False),
    sa.Column('version_policy', sa.String(length=16), nullable=False),
    sa.Column('data_asset_id', sa.String(length=64), nullable=False),
    sa.Column('scope', sa.String(length=128), nullable=False),
    sa.Column('sampling', sa.String(length=64), nullable=False),
    sa.Column('data_window', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_asset',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('record_meaning', sa.String(length=128), nullable=False),
    sa.Column('record_id_field', sa.String(length=64), nullable=False),
    sa.Column('time_field', sa.String(length=64), nullable=False),
    sa.Column('lifecycle', sa.String(length=16), nullable=False),
    sa.Column('health', sa.String(length=16), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('rows', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('result_rule_set',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evaluation_priority', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('quality_result', sa.Column('transcript', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.add_column('quality_result', sa.Column('rules_version', sa.Integer(), nullable=True))
    op.add_column('quality_result', sa.Column('review_history', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quality_result', 'review_history')
    op.drop_column('quality_result', 'rules_version')
    op.drop_column('quality_result', 'transcript')
    op.drop_table('result_rule_set')
    op.drop_table('data_asset')
    op.drop_table('analysis_task')
    # ### end Alembic commands ###
