"""run_agent_id

Revision ID: 7f42d060212d
Revises: 7e53a7b17925
Create Date: 2026-08-24 00:47:52.586275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f42d060212d'
down_revision: Union[str, Sequence[str], None] = '7e53a7b17925'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run', sa.Column('agent_id', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_run_agent_id'), 'run', ['agent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_run_agent_id'), table_name='run')
    op.drop_column('run', 'agent_id')
    # ### end Alembic commands ###
