"""node_run/run_event cascade on run delete

Revision ID: 81ceb536a687
Revises: d206117cd502
Create Date: 2026-08-22 16:38:03.754637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81ceb536a687'
down_revision: Union[str, Sequence[str], None] = 'd206117cd502'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('node_run_run_id_fkey'), 'node_run', type_='foreignkey')
    op.create_foreign_key(None, 'node_run', 'run', ['run_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('run_event_run_id_fkey'), 'run_event', type_='foreignkey')
    op.create_foreign_key(None, 'run_event', 'run', ['run_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'run_event', type_='foreignkey')
    op.create_foreign_key(op.f('run_event_run_id_fkey'), 'run_event', 'run', ['run_id'], ['id'])
    op.drop_constraint(None, 'node_run', type_='foreignkey')
    op.create_foreign_key(op.f('node_run_run_id_fkey'), 'node_run', 'run', ['run_id'], ['id'])
    # ### end Alembic commands ###
