"""resource_management_p1

Revision ID: 8786490574e4
Revises: 7bb304f4669b
Create Date: 2026-08-23 17:38:17.298693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import uuid

# revision identifiers, used by Alembic.
revision: str = '8786490574e4'
down_revision: Union[str, Sequence[str], None] = '7bb304f4669b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_change_log',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('resource_type', sa.String(length=16), nullable=False),
    sa.Column('resource_id', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_change_log_resource_id'), 'resource_change_log', ['resource_id'], unique=False)
    op.create_index(op.f('ix_resource_change_log_resource_type'), 'resource_change_log', ['resource_type'], unique=False)
    op.create_table('datasource',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('connection_id', sa.String(length=32), nullable=True),
    sa.Column('location', sa.String(length=128), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('health', sa.String(length=16), nullable=False),
    sa.Column('last_check_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['connection.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mcp_server',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('transport', sa.String(length=8), nullable=False),
    sa.Column('command', sa.String(length=256), nullable=False),
    sa.Column('connection_id', sa.String(length=32), nullable=True),
    sa.Column('env', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('health', sa.String(length=16), nullable=False),
    sa.Column('discovered_tools', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_test_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['connection.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_definition',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('data_asset_id', sa.String(length=32), nullable=False),
    sa.Column('field_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('eligibility', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('lifecycle', sa.String(length=16), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['data_asset_id'], ['data_asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_definition_data_asset_id'), 'data_definition', ['data_asset_id'], unique=False)
    op.create_table('knowledge_source',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('embedding_model_id', sa.String(length=32), nullable=True),
    sa.Column('source_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('health', sa.String(length=16), nullable=False),
    sa.Column('slice_count', sa.Integer(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['embedding_model_id'], ['model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('analysis_task', sa.Column('data_definition_id', sa.String(length=32), nullable=True))
    op.add_column('call_record', sa.Column('target_type', sa.String(length=16), nullable=False, server_default=''))
    op.add_column('connection', sa.Column('protocol', sa.String(length=16), nullable=False, server_default='http-api'))
    op.add_column('connection', sa.Column('endpoint', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='{}'))
    op.add_column('data_asset', sa.Column('datasource_id', sa.String(length=32), nullable=True))
    op.add_column('data_asset', sa.Column('location', sa.String(length=128), nullable=False, server_default=''))
    op.create_foreign_key(None, 'data_asset', 'datasource', ['datasource_id'], ['id'])
    op.add_column('eval_sample', sa.Column('data_asset_id', sa.String(length=32), nullable=True))
    op.add_column('workflow_version', sa.Column('mcp_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='[]'))
    op.add_column('workflow_version', sa.Column('knowledge_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='[]'))

    # 存量回填：每个 DataAsset 补建一个 Ready 的 DataDefinition，任务挂接
    conn = op.get_bind()
    rows = conn.execute(sa.text("SELECT id, name, revision FROM data_asset")).fetchall()
    for r in rows:
        def_id = uuid.uuid4().hex
        conn.execute(sa.text(
            "INSERT INTO data_definition (id, name, data_asset_id, field_schema, eligibility, lifecycle, revision, created_at, updated_at) "
            "VALUES (:id, :name, :aid, '[]', '[]', 'Ready', :rev, now(), now())"),
            {"id": def_id, "name": r.name, "aid": r.id, "rev": r.revision or 1})
        conn.execute(sa.text("UPDATE analysis_task SET data_definition_id = :did WHERE data_asset_id = :aid AND data_definition_id IS NULL"),
                     {"did": def_id, "aid": r.id})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_version', 'knowledge_refs')
    op.drop_column('workflow_version', 'mcp_refs')
    op.drop_column('eval_sample', 'data_asset_id')
    op.drop_constraint(None, 'data_asset', type_='foreignkey')
    op.drop_column('data_asset', 'location')
    op.drop_column('data_asset', 'datasource_id')
    op.drop_column('connection', 'endpoint')
    op.drop_column('connection', 'protocol')
    op.drop_column('call_record', 'target_type')
    op.drop_column('analysis_task', 'data_definition_id')
    op.drop_table('knowledge_source')
    op.drop_index(op.f('ix_data_definition_data_asset_id'), table_name='data_definition')
    op.drop_table('data_definition')
    op.drop_table('mcp_server')
    op.drop_table('datasource')
    op.drop_index(op.f('ix_resource_change_log_resource_type'), table_name='resource_change_log')
    op.drop_index(op.f('ix_resource_change_log_resource_id'), table_name='resource_change_log')
    op.drop_table('resource_change_log')
    # ### end Alembic commands ###
