"""agent avatar

Revision ID: b4ebdf4445dd
Revises: f65b7ffd78a7
Create Date: 2026-08-22 15:19:39.900303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4ebdf4445dd'
down_revision: Union[str, Sequence[str], None] = 'f65b7ffd78a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent', sa.Column('avatar', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent', 'avatar')
    # ### end Alembic commands ###
