"""run fk set null on workflow delete

Revision ID: d206117cd502
Revises: b4ebdf4445dd
Create Date: 2026-08-22 16:36:29.126634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd206117cd502'
down_revision: Union[str, Sequence[str], None] = 'b4ebdf4445dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('run_workflow_id_fkey'), 'run', type_='foreignkey')
    op.drop_constraint(op.f('run_workflow_version_id_fkey'), 'run', type_='foreignkey')
    op.create_foreign_key(None, 'run', 'workflow_version', ['workflow_version_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'run', 'workflow', ['workflow_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'run', type_='foreignkey')
    op.drop_constraint(None, 'run', type_='foreignkey')
    op.create_foreign_key(op.f('run_workflow_version_id_fkey'), 'run', 'workflow_version', ['workflow_version_id'], ['id'])
    op.create_foreign_key(op.f('run_workflow_id_fkey'), 'run', 'workflow', ['workflow_id'], ['id'])
    # ### end Alembic commands ###
