"""resource lock

Revision ID: f65b7ffd78a7
Revises: bc9a44b8d433
Create Date: 2026-08-22 04:04:59.363757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f65b7ffd78a7'
down_revision: Union[str, Sequence[str], None] = 'bc9a44b8d433'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_lock',
    sa.Column('resource_id', sa.String(length=64), nullable=False),
    sa.Column('ws_id', sa.String(length=16), nullable=False),
    sa.Column('user_name', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('resource_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resource_lock')
    # ### end Alembic commands ###
